### ISSUE TITLE
Travis is not working.

### ISSUE THREAD

**Issue by bende01** [BME-MIT-IET/Szoftver-projekt-masters-iet-2019#1]
Nem működik a travis.

**Comment by AcidicNut** [comment]
Dolgozok rajta. (Working on it.) :)

**Comment by 1nco** [comment]
`> immutable@4.0.0-rc.12 test C:\projects\szoftver-projekt-masters-iet-2019
> run-s format build lint testonly test:types:*
> immutable@4.0.0-rc.12 format C:\projects\szoftver-projekt-masters-iet-2019
> prettier --single-quote --trailing-comma=es5 --write "{__tests__,src,pages/src,pages/lib,perf,resources}/**/*{\.js,\.ts}"
[error] No matching files. Patterns tried: {__tests__,src,pages/src,pages/lib,perf,resources}/**/*{\.js,\.ts} !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "format"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! immutable@4.0.0-rc.12 format: `prettier --single-quote --trailing-comma=es5 --write "{__tests__,src,pages/src,pages/lib,perf,resources}/**/*{\.js,\.ts}"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the immutable@4.0.0-rc.12 format script 'prettier --single-quote --trailing-comma=es5 --write "{__tests__,src,pages/src,pages/lib,perf,resources}/**/*{\.js,\.ts}"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the immutable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prettier --single-quote --trailing-comma=es5 --write "{__tests__,src,pages/src,pages/lib,perf,resources}/**/*{\.js,\.ts}"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs immutable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls immutable
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\szoftver-projekt-masters-iet-2019\npm-debug.log
ERROR: "format" exited with 1.
npm ERR! Test failed.  See above for more details.
Command exited with code 1`

**Comment by 1nco** [comment]
Travis helyett AppVeyorral is próbálkoztam, de nem sikerült felconfigolni az feljebbb látható hiba miatt egyik CI se működik.  Az AppVeyor szerint az Immutable package-el van a baj.

**Comment by AcidicNut** [comment]
Tekintettel arra hogy egyikünk sem tudja biztosan hogy hogyan lehet megoldani, ezért zárom az issue-t.
