### ISSUE TITLE
super() must be invoked in any derived class constructor.

### ISSUE THREAD

**Issue by ntopee** [BME-MIT-IET/Szoftver-projekt-masters-iet-2019#5]
A származtatott osztályok konstruktorában kötelező super()-el meghívni a szülő konstruktorát is, ez a projektben az összes konstruktorból hiányzik. Így is működik, ezeket javítsuk?

**Comment by 1nco** [comment]
szerintem nem kell javítani őket, de ha valaki érez magában affinitást erre, akkor mindenképpen szebb lenne tőle a kód.
